### ISSUE TITLE
Erro versão 5#

### ISSUE THREAD

**Issue by Jtruculo** [Tomamais/VbaFormBuilder#11]
Olá Tomaz, Boa tarde!
Estou com PC 64 bits, Excel 2010 e está dando o seguinte erro:

VERSION 5#
**Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmConstrutor** '< -------------- 
   Caption = "Construtor de Formulários"
   ClientHeight = 4212
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 7920
   **OleObjectBlob   =   "ufmConstrutor.frx":0000** '< -------------- 
   StartUpPosition = 1    'CenterOwner
End

**Comment by Tomamais** [comment]
Duplicate of #9

**Comment by Tomamais** [comment]
Mais instruções aqui: https://www.youtube.com/watch?v=N5qsCMJx3Ug
