### ISSUE TITLE
Aplicativo

### ISSUE THREAD

**Issue by PZRG** [Tomamais/VbaFormBuilder#13]
Boa tarde

Nem atraves do repositorio o arquivo funcionou. No video apresentado deve ser uma beleza trabalhar com esse aplicativo. Uma pena não funcionar na minha maquina.

Abraços

Pedro

**Comment by Tomamais** [comment]
Pedro,

Como esta área é para reportagem de defeitos no aplicativo e no seu caso não vi nenhum detalhamento sobre, estou fechando o ticket. 

Quando for abrir um ticket, peço que por favor informe:

- Versão do Windows utilizada
- Versão do Excel utilizada
- Detalhes do bug (em qual momento ocorre, qual a mensagem de erro, etc)
