### ISSUE TITLE
Erro ao clicar em NOVO

### ISSUE THREAD

**Issue by LucioMatias** [Tomamais/VbaFormBuilder#14]
Está retornando erro ao tentar cadastrar um novo registro, quando clico no botão "Novo", conforme mostra na imagem anexada.
O que estou fazendo de errado?

![erro](https://user-images.githubusercontent.com/38002701/50085040-a4715d00-01d7-11e9-8bf2-4e606943643e.png)

**Comment by Tomamais** [comment]
Pode confirmar se isso acontece quando o banco de dados está vazio? Se sim, já tem um ticket para isso: #1

**Comment by LucioMatias** [comment]
Também pensei que fosse isso, mas existe um registro no banco de dados.
E o erro ocorre quando clico no botão novo, mesmo antes de salvar algum
dado.



Em seg, 17 de dez de 2018 às 16:36, Tomás <notifications@github.com>
escreveu:

**Comment by Tomamais** [comment]
Pode mandar o banco de dados para eu dar uma olhada? Só o create table com uma linha de dados já ajuda

**Comment by LucioMatias** [comment]
Segue o banco.

**Comment by LucioMatias** [comment]
Segue o banco.

Em seg, 17 de dez de 2018 às 17:09, Tomás <notifications@github.com>
escreveu:

**Comment by Tomamais** [comment]
reabrindo no ticket. Consegue mandar um link do dropbox/onedriver/googledrive?

**Comment by LucioMatias** [comment]
Segue link do Dropbox:
https://www.dropbox.com/s/a2orhqzidb72kwi/Banco.accdb?dl=0

**Comment by LucioMatias** [comment]
Olá tomás, alguma solução?

**Comment by Tomamais** [comment]
@LucioMatias testei aqui e funcionou. Eu explico isso no vídeo de apresentação. Você não pode abrir o formulário de cadastro diretamente. É preciso utilizar a função que no seu caso está em modtblClientes -> AbreFormtblClientes. Ela cria todo o contexto do objeto da tabela e os cursores em memória que faz o aplicativo funcionar. Fechando o ticket
