### ISSUE TITLE
Erro Gerar novo formulario

### ISSUE THREAD

**Issue by joinfi0467** [Tomamais/VbaFormBuilder#15]
Boa tarde. Achei ótimo e muito interessante seu trabalho, pelo que dei uma olhada dá pra fazer muita coisa com ele, porém ao tentar executar o arquivo de downloads está dando a seguinte mensagem: "Não é possível executar a macro 'VbaFormBuilder.xlsm'. 
Talvez ela não esteja disponível nesta pasta trabalho ou todas as macros estejam desabilitadas".
OBS: Minhas macros estão habilitadas para todos os tipos de macros, pelo que olhei no Porject Explorer não carrega o formulário selecionar banco de dados. Porque quando dou  click em iniciar dá mensagem.

**Comment by joinfi0467** [comment]
OBS: Meu PC é Windows10 64 bits. Office 2013

**Comment by Tomamais** [comment]
@joinfi0467 acho que deve ser isso: https://www.youtube.com/watch?v=VM_xK0PnmQs

**Comment by joinfi0467** [comment]
Caro Tomas Vasquez, não consegui fazer funcionar mesmo com esse vídeo de errata. veja no anexo não aparece os formularios.
![Capturar](https://user-images.githubusercontent.com/48739409/54873937-11d8ef00-4dc0-11e9-8b98-b34bfe0522a5.JPG)

**Comment by joinfi0467** [comment]
Bom dia, Tomas Vasquez.
Infelizmente ainda assim não consegui fazer funcionar postei as elas no
https://github.com/Tomamais/VbaFormBuilder/issues/15, porem não tive
nenhuma resposta.
Minha pergunta é teria como enviar de outra forma ou fazer um vídeo passo a
passo desde o site até o pleno funcionamento, habilitando tudo que precisa
ser habilitado no excel, ou me encaminhar de outra forma com algumas dicas
do que precisa estar habilitado no excel além das macros. Pedindo porque
achei o máximo este seu programa VBAFormBuilder.
Abraço e bom fim  de semana
Att Inácio
(48) 998191945

Em sáb, 23 de mar de 2019 às 17:11, Tomás <notifications@github.com>
escreveu:

**Comment by joinfi0467** [comment]
Caro Tomas Vasquez, você me respondeu com este vídeo em 23/03/2019, porém
mesmo assim não consegui fazer funcionar. Coloquei no site
https://github.com/Tomamais/VbaFormBuilder/issues/15 as telas que dei print.
Att
Inácio
(48)998191945

Em sáb, 6 de abr de 2019 às 08:49, Jose Inacio Filho <joinfi0467@gmail.com>
escreveu:

**Comment by joinfi0467** [comment]
Bom dia.
Tomas Vasquez
Não consegui fazer funcionar mas ainda não desisti do seu VbaFormBuilder.
Se tiver uma forma de me enviar sem se baixa pelo site, com mais algumas
dicas agradeço.
Pelo que notei no meu ele não carrega os formulários.
Este vídeo de errata já tinha visto porém não foi suficiente.
Mas tenho certeza que vou conseguir com mais algumas dicas.
No site do GitHub postei a tela do VBA
Att



Em sáb, 23 de mar de 2019 às 17:11, Tomás <notifications@github.com>
escreveu:

**Comment by Tomamais** [comment]
@joinfi0467 acabei deixando o projeto de lado por tempo. De toda forma, não consegui ver as imagens. Vou encerrar o ticket por enquanto. Se o problema persistir, peço que abra um novo.
