### ISSUE TITLE
Não carrega todos os códigos

### ISSUE THREAD

**Issue by JCabral2000** [Tomamais/VbaFormBuilder#16]

**Comment by JCabral2000** [comment]
**Skipping file ufmConstrutor.frx
Skipping file ufmSelecionaBanco.frx**
removing modInit
Invoking 'Build.importComponents'with Application.Ontime with delay 00:00:03
almost finished importing code for vbaProject
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\modAbrir.bas
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\modAccess.bas
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\modAuxiliar.bas
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\modInit.bas
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\modUserForm.bas
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\ufmConstrutor.frm
Importing component from  C:\Users\Joka\Desktop\VbaFormBuilder-master\src\VbaFormBuilder.xlsm\ufmSelecionaBanco.frm
Finished importing code for vbaProject﻿

**Não cria as userform's**

**Comment by JCabral2000** [comment]
VERSION 5#
**Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmConstrutor**
   Caption = "Construtor de Formulários"
   ClientHeight = 4212
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 7920
   **OleObjectBlob   =   "ufmConstrutor.frx":0000**
   StartUpPosition = 1    'CenterOwner
End

**Comment by Tomamais** [comment]
@JCabral2000 veja se é isso: https://www.youtube.com/watch?v=N5qsCMJx3Ug

**Comment by JCabral2000** [comment]
É isso, só não sei como fazer para baixar pelo aplicativo. Tem algum vídeo explicando?

**Comment by Tomamais** [comment]
https://www.youtube.com/watch?v=kt9XqKSpHsk

**Comment by JCabral2000** [comment]
Já consegui gerar direito o meu formulário.
Só que agora dá-me um erro quando corro o formulário - "Erro de conversão do tipo de dados."
Atendendo a que nenhum campo é obrigatório este erro só desaparece quando preencho dois determinados campos, que são os únicos que não são do tipo String, são números de telefone.
Se disponibilizar um email posso enviar para testar e ver o erro. Obrigado

**Comment by Tomamais** [comment]
O gerador na versão atual não suporta todos os tipos de dados. Qual a estrutura da sua tabela?

**Comment by JCabral2000** [comment]
A estrutura é muito simples, tem 11 campos, 1 de numeração automática, 8 de Texto 2 de número.
Nenhum campo é obrigatório.
[Captura.pdf](https://github.com/Tomamais/VbaFormBuilder/files/3131032/Captura.pdf)

**Comment by JCabral2000** [comment]
A estrutura é muito simples, tem 11 campos, 1 de numeração automática, 8 de Texto 2 de número.
Nenhum campo é obrigatório.

[VBAFBuilder Teste.zip](https://github.com/Tomamais/VbaFormBuilder/files/3131040/VBAFBuilder.Teste.zip)

**Comment by Tomamais** [comment]
Desculpe a demora. Deixei o projeto de lado por um tempo. De volta, baixei o arquivo e testei. Rodou certinho. Estou anexando o arquivo de resultado e fechando o ticket.
[BD_Vinhos.zip](https://github.com/Tomamais/VbaFormBuilder/files/4100340/BD_Vinhos.zip)
