### ISSUE TITLE
ComboBox na inclusão de registro

### ISSUE THREAD

**Issue by mironlourenco** [Tomamais/VbaFormBuilder#17]
Tomaz, vc é um gênio (mas ainda não é/somos perfeitos...rssrs). Então, vamos lá:

Tenho um BD com 2 tabelas. Na 2a. tabela tenho um campo "X" cujos valores vêm de um campo "Y" da 1a. tabela via "Assistente de Pesquisa". Qdo gero o form no VbaFormBuilder utilizando a 2a. tabela, os valores no campo "X" aparecem normalmente navegando pelo Form (próximo registro, registro anterior, primeiro registro e último registro). Porém, quando quero inserir um novo registro (ou alterar um existente) e abro o ComboBox não aparece nenhum valor. Como resolver isso?

**Comment by mironlourenco** [comment]
Bom dia, Tomás (desculpe-me, escrevi seu nome errado no primeiro post).

Consegui fazer alterando as macros contidas na planilha criada pelo VbaFormBuilder.
Primeiro, adaptei o seguinte código para carregar o ComboBox1 (grato ao colega Rsantana28 no link http://www.tomasvasquez.com.br/forum/viewtopic.php?t=3393)

Public Sub Carrega_ComboBox1()    
    
    Dim dt As Recordset
    Dim sql As String
    Dim opcao As String
        
    sql = "SELECT [Campo Y] FROM [Nome da 1a. tabela]"
    Set dt = cls[Nome do módulo de classe criado pelo VbaFormBuilder].CurrentDb.OpenRecordset(sql)
    opcao = Me.ComboBox1.Value
    Me.ComboBox1.Clear
    
    Do While Not dt.EOF
        Me.ComboBox1.AddItem dt.Fields(0) & ""
        dt.MoveNext
    Loop
    
    Me.ComboBox1.Value = opcao

End Sub

Depois, inseri o código acima nos códigos dos botões "Novo" e "Alterar" e também no Form de Pesquisa.

**Comment by Tomamais** [comment]
Resolvido pelo próprio usuário :)
