### ISSUE TITLE
ERRO DE COMPILAÇÃO: Inválido fora de um procedimento

### ISSUE THREAD

**Issue by Andreluoliveira** [Tomamais/VbaFormBuilder#18]
VERSION 5#
Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmSelecionaBanco
   Caption = "Selecionar o banco de dados"
   ClientHeight = 4380
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 6456
   OleObjectBlob   =   "ufmSelecionaBanco.frx":0000
   StartUpPosition = 1    'CenterOwner
End

**Comment by Tomamais** [comment]
@Andreluoliveira quais os passos para reproduzir o erro?

**Comment by Tomamais** [comment]
Fechando por inatividade
