### ISSUE TITLE
bloco With

### ISSUE THREAD

**Issue by nhyky12** [Tomamais/VbaFormBuilder#2]
Error quando se tenta fazer qualquer coisa: A variável do objeto ou a variável do bloco With não foi definida.
O formularizar de cadastro inicia inicializa vazio. Deve ser por isso que da erro. Ele nao esta captando o primeiro item.
Mesmo apos colocando o primeiro cadastro ele inicia sem preencher automaticamente o primeiro item.
Para o formulário de cadastro funcionar, tenho que ir em pesquisar para ele chamar um item qualquer , ai ele começar a funcionar.

**Comment by Tomamais** [comment]
@nhyky12 pode colocar a estrutura da tabela para poder replicar o erro?

**Comment by nhyky12** [comment]
Que faço depois?

Em Qua, 18 de abr de 2018 14:08, Tomás <notifications@github.com> escreveu:

**Comment by Tomamais** [comment]
desculpe. Pode colocar a estrutura da tabela aqui? Quais campos/tipos

**Comment by nhyky12** [comment]
São as mesma do seu modelo. Só baixei gerei o formulário usei o arquivo do
access fornecido. Não fiz nenhuma alteração.

Em Qua, 18 de abr de 2018 14:12, Tomás <notifications@github.com> escreveu:

**Comment by Tomamais** [comment]
acabei de fazer um teste aqui e funcionou perfeitamente. Pode anexar o arquivo do access aqui?

**Comment by nhyky12** [comment]
Não estou conseguindo anexa, eivando por: [REMOVIDO]

**Comment by Tomamais** [comment]
o 4shared requer registro. Peço que use outro mecanismo de compartilhamento mais seguro como onedrive ou google drive

**Comment by nhyky12** [comment]
https://drive.google.com/file/d/1qCDCkQJoWdJj8x0ZacC6uaoMYf02TXZN/view?usp=sharing

**Comment by Tomamais** [comment]
Funcionou aqui perfeitamente, sem errors. Segue anexo o arquivo gerado:
[Atendimentos.zip](https://github.com/Tomamais/VbaFormBuilder/files/1935967/Atendimentos.zip)

O que nos leva às próximas perguntas:

Qualquer a versão dos seguintes softwares:
Windows (32/64)
Office (32/64)

**Comment by nhyky12** [comment]
Descobri o erro anterior, eu não estava iniciando o formulário pelo modulo. Resolvido.

**Comment by Tomamais** [comment]
maravilha! Fechando o ticket!
