### ISSUE TITLE
FOTOS

### ISSUE THREAD

**Issue by nhyky12** [Tomamais/VbaFormBuilder#3]
SERIA POSSÍVEL INSERIR FOTOS (3).

**Comment by Tomamais** [comment]
O cadastro com fotos eh uma implemetacao futura. Da ate para pensar que eh uma outra versao do aplicativo dado a complexidade de fazer isso com o Access ja que ele suporta armazenamento de arquivos de imagem como objetos complexos. Vou deixar o ticket fechado por enquanto haja vista que ainda ha muito a melhorar no cadastro em si. Valeu pela sugestao mesmo assim.

**Comment by Tomamais** [comment]
Fechando o ticket
