### ISSUE TITLE
Erro ao cadastrar dado assim que o form é aberto

### ISSUE THREAD

**Issue by roldnei** [Tomamais/VbaFormBuilder#4]
Olá,

Primeiramente parabéns pelo belo trabalho. Não consegui resolver então vou relatar aqui.

Assim que abre o formulário e todos os txtbox estão em branco, ao clicar no botão "Novo" aparece um erro de compilação "Erro de objeto with ou variável não definido". 

Aparentemente a variável declarada como tabela, nesse caso, está com valor "nothing" impossibilitando a criação de uma nova linha.

Realmente não sei como resolver isso.

**Comment by Tomamais** [comment]
Pode colocar anexar o banco de dados utilizado aqui? Links para o dropbox/onedrive/google drive sao preferiveis

**Comment by roldnei** [comment]
Coloquei os dois.
Acontece para o primeiro cadastro assim que o form abre.

https://drive.google.com/open?id=1wG9-nxHrCzD6qlwfK5kR-ANAVVCN2zRZ

**Comment by Tomamais** [comment]
Gerei um novo cadastro a partir do bd que enviou. Funcionou perfeitmante. Ja existe um ticket para tratar a geracao do cadastro com o banco de dados vazio: https://github.com/Tomamais/VbaFormBuilder/issues/1

Por enquanto, eh preciso ter pelo menos um registro na tabela. Do contrario, a geracao do cadastro falhara.

Pode testar desta forma?

**Comment by roldnei** [comment]
Tentei novamente, agora com dois registros no banco de dados.  E aconteceu de novo.

Ao clicar no checkbox ("novo") assim que abre o form, aparece o "erro em tempo de execução 91", o mesmo que eu tinha comentado.

Você usou o que eu te enviei ou gerou um novo formulário com o vbaformbuilder? Poderia testar gerando um novo formulário?

O que eu te enviei, inseri um IF no evento click do checkbox "novo". Poderia fazer esse teste?

**Comment by Tomamais** [comment]
Acabei de gererar o cadastro e adicionei um novo registro. Funcionou perfeitamente. Segue anexo o app funcionando.
[orcamentos.zip](https://github.com/Tomamais/VbaFormBuilder/files/1965161/orcamentos.zip)

**Comment by roldnei** [comment]
Mesmo erro, estou usando o office 2016 plus.  Não sei o que pode ser. 

Pelo seu vídeo no youtube, assim que você abre o form carrega o primeiro dado gravado. Nessa versão disponibilizada também ocorre isso? O meu não está carregando logo que abre, acho que esse é o problema.

**Comment by Tomamais** [comment]
Testei num Office 2013 e num Office 2016 (365). Funcionou perfeitamente.

Você está abrindo o formulário pela macro AbreFormORCAMENTO?

**Comment by roldnei** [comment]
Matou a pau! Resolvido.

Mais uma vez parabéns pelo brilhante trabalho. Vou contribuir na medida do possível.

**Comment by Tomamais** [comment]
Maravilha! Fechando o ticket!
