### ISSUE TITLE
O aplicativo dá erro no Excel 2007 e 2010

### ISSUE THREAD

**Issue by Jtruculo** [Tomamais/VbaFormBuilder#9]
Tomas,
Boa tarde!

A versão 5# não funciona no excel 2007 e 2010.
Existe alguma instrução adicional para esta versão.

Desde já obrigado.

**Comment by Tomamais** [comment]
Testei nas versoes 2013 e 2016 com sucesso. Qual a mensagem de erro?

**Comment by Jtruculo** [comment]
Ocorre o seguinte,

**Botão Importar código:** Importação realizada com sucesso - Ok
**Botão Iniciar:** Erro de compilação: Inválido fora de um procedimento

Segue a parte do códico que aponta após o erro:

VERSION 5#
**Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmConstrutor**
   Caption = "Construtor de Formulários"
   ClientHeight = 4212
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 7920
   **OleObjectBlob   =   "ufmConstrutor.frx":0000**
   StartUpPosition = 1    'CenterOwner
End

E:

VERSION 5#
**Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmSelecionaBanco**
   Caption = "Selecionar o banco de dados"
   ClientHeight = 4380
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 6456
   **OleObjectBlob   =   "ufmSelecionaBanco.frx":0000**
   StartUpPosition = 1    'CenterOwner
End

**Comment by Tomamais** [comment]
O aplicativo foi desenvolvido utilizando o Excel 2016 e testado no Excel 2013. Dado que este foi lançado em 2018, vou considerar que o suporte será dando oficialmente a partir do Excel 2013. O esforço para fazê-lo funcionar em versões anteriores a esta terá que vir da própria comunidade, já que o custo para manter versões diferentes do Excel extrapola o objetivo do projeto.

De toda forma, o bug ficará aberto até que alguém se proponha a resolvê-lo.

**Comment by YukiMaru-5** [comment]
Estou com o mesmo erro descrito pelo colega Jtruculo, sendo que estou utilizando Excel 2016 Professional. Teria alguma sugestão do que fazer?

**Comment by Tomamais** [comment]
@YukiMaru-5 descreva todos os passos executados até o momento da ocorrência do erro

**Comment by YukiMaru-5** [comment]
- Macros habilitadas (já estão, sempre...);
- Habilitei o "Confiar no acesso ao modelo de objeto de projeto VBA"
- Botão Importar código: Importação realizada com sucesso - Ok
- Botão Iniciar: Erro de compilação: Inválido fora de um procedimento
Ao dar erro, o "5#" é selecionado e as duas linhas destacadas abaixo ficam em vermelho:

VERSION 5#
**_Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} ufmConstrutor_**
   Caption = "Construtor de Formulários"
   ClientHeight = 4212
   ClientLeft = 108
   ClientTop = 456
   ClientWidth = 7920
   **_OleObjectBlob   =   "ufmConstrutor.frx":0000_**
   StartUpPosition = 1    'CenterOwner
End

Entendo que a linha do Begin, está dando erro devido ao uso de colchetes "{ }".
![erro vba](https://user-images.githubusercontent.com/39289852/40073495-5d428e74-584d-11e8-9ff4-689100cf8979.PNG)

**Comment by Tomamais** [comment]
Pode tentar importar manualmente para ver o que acontece?

**Comment by YukiMaru-5** [comment]
Tomás, ocorre o mesmo erro.
Por acaso, poderia ter algo com o fato do vba estar trocando 5.00 por 5# ?

**Comment by Tomamais** [comment]
acabou de replicar o erro aqui. Ele acontece quando voce baixa o arquivo zip direto no github e o descompacta. Neste caso, a importacao do codigo falhara. Presumo que seja algo relacionado com a forma com a qual o git faz a compressao dos arquivos. Se utilizar o git para clonar o repositorio, a importacao funcionara. 

Voce tem instrucoes de como clonar no repositorio aqui: https://www.youtube.com/watch?v=kt9XqKSpHsk

**Comment by Tomamais** [comment]
Uma vez que este nao eh um problema do aplicativo e sim da plataforma, estou fechando o ticket.

**Comment by YukiMaru-5** [comment]
Sr. Tomás, funcionou perfeitamente!
Com meus conhecimentos limitados, só posso dizer uma coisa sobre este erro:   Oo

De qualquer forma, muito obrigado. Tanto pela ajuda neste problema, como por todo material e tutoriais que você disponibiliza.

**Comment by Jtruculo** [comment]
YukiMaru-5 td bem! Vc pode fazer a gentileza de postar a planilha VbaFormBuilder que vc clonou, estou sem notebook de 64 bits para baixar o Github. Agradeço.

**Comment by Tomamais** [comment]
@Jtruculo siga os passos do vídeo que passei acima. Isso evitará que você tenha problemas no futuro.
